apiVersion: batch/v1
kind: Job
metadata:
  name: ml-spark-job
  labels:
    app: ml-spark-job
spec:
  template:
    metadata:
      labels:
        app: ml-spark-job
    spec:
      serviceAccountName: spark-sa
      containers:
      - name: spark-job
        image: <ECR_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/ml-crash-course-spark:latest
        env:
        - name: S3_BUCKET
          value: "ml-crash-course-data"
        - name: S3_KEY
          value: "House_Rent_Dataset.csv"
        - name: AWS_REGION
          value: "us-east-2"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Never
  backoffLimit: 3 