apiVersion: v1
kind: Service
metadata:
  name: model-api
spec:
  type: LoadBalancer
  selector:
    app: model-api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000 